[phases.setup]
nixPkgs = ['openjdk21', 'maven']

[phases.install]
cmds = [
  'export JAVA_HOME=/usr/lib/jvm/java-21-openjdk',
  'export PATH=$JAVA_HOME/bin:$PATH',
  'export JAVA_VERSION=21',
  'java -version',
  './mvnw -version',
  './mvnw clean package -DskipTests'
]

[phases.build]
cmds = ['echo "Build completed successfully"']

[start]
cmd = 'java -jar target/Travner-0.0.1-SNAPSHOT.jar'
