spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:TravnerDB}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

server:
  port: ${PORT:8080}

app:
  upload:
    dir: ${APP_UPLOAD_DIR:${user.home}/travner-uploads}

# Actuator configuration for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Application info for actuator
info:
  app:
    name: Travner API
    description: Travel blog and experience sharing platform
    version: 1.0.0
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"
