spring:
  application:
    name: travner

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:TravnerDB}
      auto-index-creation: false  # Disable auto-index creation to prevent startup issues
      # Connection pool settings optimized for production
      options:
        max-connections-per-host: ${MONGO_MAX_CONNECTIONS:50}
        min-connections-per-host: ${MONGO_MIN_CONNECTIONS:5}
        max-wait-time: ${MONGO_MAX_WAIT_TIME:30000}
        connect-timeout: ${MONGO_CONNECT_TIMEOUT:10000}
        socket-timeout: ${MONGO_SOCKET_TIMEOUT:30000}
        server-selection-timeout: ${MONGO_SERVER_SELECTION_TIMEOUT:30000}
        # Production-ready settings
        ssl: true
        ssl-invalid-hostname-allowed: false
        retry-writes: true
        retry-reads: true
        # Connection resilience
        max-connection-idle-time: 60000
        max-connection-life-time: 0
        heartbeat-frequency: 10000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

app:
  upload:
    dir: ${APP_UPLOAD_DIR:${user.home}/travner-uploads}

  # CORS Configuration - Allow all origins
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: false

  # Chat Configuration
  chat:
    message:
      max-length: ${CHAT_MESSAGE_MAX_LENGTH:4000}
      max-attachments: ${CHAT_MESSAGE_MAX_ATTACHMENTS:5}
    rate-limit:
      messages-per-minute: ${CHAT_RATE_LIMIT_MESSAGES:60}
      typing-cooldown-seconds: ${CHAT_TYPING_COOLDOWN:2}
    broker:
      type: ${CHAT_BROKER_TYPE:simple} # simple or external
      relay-host: ${CHAT_RELAY_HOST:localhost}
      relay-port: ${CHAT_RELAY_PORT:61613}
      relay-login: ${CHAT_RELAY_LOGIN:guest}
      relay-passcode: ${CHAT_RELAY_PASSCODE:guest}

# Actuator configuration for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Application info for actuator
info:
  app:
    name: Travner API
    description: Travel blog and experience sharing platform
    version: 1.0.0
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"

logging:
  level:
    org.adnan.travner: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
    org.springframework.data.mongodb: ${MONGO_LOG_LEVEL:WARN}
    org.springframework.web: ${WEB_LOG_LEVEL:WARN}
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:logs/travner.log}
    max-size: 10MB
    max-history: 30

# Security configuration - use environment variables in production
security:
  user:
    name: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
    roles: ADMIN



