spring:
  application:
    name: travner

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:TravnerDB}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

app:
  upload:
    dir: ${APP_UPLOAD_DIR:${user.home}/travner-uploads}

  # CORS Configuration
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000,https://travner.vercel.app}
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

  # Chat Configuration
  chat:
    message:
      max-length: ${CHAT_MESSAGE_MAX_LENGTH:4000}
      max-attachments: ${CHAT_MESSAGE_MAX_ATTACHMENTS:5}
    rate-limit:
      messages-per-minute: ${CHAT_RATE_LIMIT_MESSAGES:60}
      typing-cooldown-seconds: ${CHAT_TYPING_COOLDOWN:2}
    broker:
      type: ${CHAT_BROKER_TYPE:simple} # simple or external
      relay-host: ${CHAT_RELAY_HOST:localhost}
      relay-port: ${CHAT_RELAY_PORT:61613}
      relay-login: ${CHAT_RELAY_LOGIN:guest}
      relay-passcode: ${CHAT_RELAY_PASSCODE:guest}

# Actuator configuration for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Application info for actuator
info:
  app:
    name: Travner API
    description: Travel blog and experience sharing platform
    version: 1.0.0
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"

logging:
  level:
    org.adnan.travner: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

security:
  user:
    name: admin
    password: admin123
    roles: ADMIN
