spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      auto-index-creation: true
      database: TravnerDB
  web:
    cors:
      allowed-origins:
        - http://localhost:4200
        - http://localhost:4201
      allowed-methods: [GET, POST, PUT, DELETE, OPTIONS]
      allowed-headers: "*"
      allow-credentials: true

server:
  port: ${PORT:8080}
  address: 0.0.0.0