spring:
  application:
    name: travner

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:TravnerDev}
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

app:
  upload:
    dir: ${APP_UPLOAD_DIR:${user.home}/travner-uploads}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200,http://localhost:5173,https://travner.vercel.app}
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

  chat:
    message:
      max-length: ${CHAT_MESSAGE_MAX_LENGTH:4000}
      max-attachments: ${CHAT_MESSAGE_MAX_ATTACHMENTS:5}
    rate-limit:
      messages-per-minute: ${CHAT_RATE_LIMIT_MESSAGES:60}
      typing-cooldown-seconds: ${CHAT_TYPING_COOLDOWN:2}

# Development logging configuration
logging:
  level:
    org.adnan.travner: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}
    org.springframework.data.mongodb: ${MONGO_LOG_LEVEL:DEBUG}
    org.springframework.web: ${WEB_LOG_LEVEL:DEBUG}
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:logs/travner-dev.log}
    max-size: 10MB
    max-history: 7

# Development actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Security configuration for development
security:
  user:
    name: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
    roles: ADMIN

# Application info for development
info:
  app:
    name: Travner API
    description: Travel blog and experience sharing platform
    version: 1.0.0
    environment: development
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"
